/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
export type ActivityDescription = string | null;

export type ActivityParameter = string | null;

export type ActivityInitiatedByUser = boolean | null;

export interface Activity {
  activity_id: number;
  name: string;
  description?: ActivityDescription;
  parameter?: ActivityParameter;
  initiated_by_user?: ActivityInitiatedByUser;
  activity_type: ActivityType;
}

export type ActivityType = (typeof ActivityType)[keyof typeof ActivityType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityType = {
  global: "global",
  campaign: "campaign",
} as const;

export interface AlreadyPaidResp {
  already_paid: boolean;
}

export type CampaignCampaignGroupId = number | null;

export type CampaignDescription = string | null;

export type CampaignEdition = string | null;

export type CampaignRequirement = string | null;

export type CampaignCollectionName = string | null;

export type CampaignChain = Chain | null;

export type CampaignVmType = VmType | null;

export type CampaignStartDate = string | null;

export type CampaignEndDate = string | null;

export type CampaignStartDateTimestamp = number | null;

export type CampaignEndDateTimestamp = number | null;

export type CampaignLimit = number | null;

export type CampaignVideoUrl = string | null;

export type CampaignLogoUrl = string | null;

export type CampaignPromoteImageUrl = string | null;

export type CampaignNftGasFee = string | null;

export type CampaignXPostUrl = string | null;

export type CampaignVideoPosterUrl = string | null;

export type CampaignEligibleMethod = string | null;

export type CampaignIsActive = boolean | null;

export type CampaignEligibleMethods = EligibleMethod[] | null;

export interface Campaign {
  campaign_id: number;
  campaign_group_id?: CampaignCampaignGroupId;
  name: string;
  description?: CampaignDescription;
  edition?: CampaignEdition;
  requirement?: CampaignRequirement;
  collection_address: string;
  collection_name?: CampaignCollectionName;
  chain?: CampaignChain;
  vm_type?: CampaignVmType;
  start_date?: CampaignStartDate;
  end_date?: CampaignEndDate;
  start_date_timestamp?: CampaignStartDateTimestamp;
  end_date_timestamp?: CampaignEndDateTimestamp;
  limit?: CampaignLimit;
  video_url?: CampaignVideoUrl;
  logo_url?: CampaignLogoUrl;
  promote_image_url?: CampaignPromoteImageUrl;
  nft_gas_fee?: CampaignNftGasFee;
  x_post_url?: CampaignXPostUrl;
  video_poster_url?: CampaignVideoPosterUrl;
  eligible_method?: CampaignEligibleMethod;
  is_ready: boolean;
  is_active?: CampaignIsActive;
  campaign_activities?: CampaignActivity[];
  eligible_methods?: CampaignEligibleMethods;
  campaign_promotions?: CampaignPromotion[];
}

export type CampaignActivityPoints = number | null;

export type CampaignActivityActivity = Activity | null;

export type CampaignActivityIsRequired = boolean | null;

export interface CampaignActivity {
  campaign_activity_id: number;
  campaign_id: number;
  activity_id: number;
  quantity: number;
  points?: CampaignActivityPoints;
  activity?: CampaignActivityActivity;
  is_required?: CampaignActivityIsRequired;
}

export type CampaignPromotionNftMerkletreeId = string | null;

export type CampaignPromotionNftImageUrl = string | null;

export type CampaignPromotionNftCollectionImageUrl = string | null;

export type CampaignPromotionNftVideoUrl = string | null;

export type CampaignPromotionNftOnChainImageUrl = string | null;

export type CampaignPromotionNftTextFrontImageUrl = string | null;

export type CampaignPromotionNftTextFrontVideoUrl = string | null;

export type CampaignPromotionPromotion = Promotion | null;

export type CampaignPromotionMintedByUser = boolean | null;

export interface CampaignPromotion {
  id: number;
  campaign_id: number;
  promotion_id: number;
  nft_merkletree_id?: CampaignPromotionNftMerkletreeId;
  nft_image_url?: CampaignPromotionNftImageUrl;
  nft_collection_image_url?: CampaignPromotionNftCollectionImageUrl;
  nft_video_url?: CampaignPromotionNftVideoUrl;
  nft_on_chain_image_url?: CampaignPromotionNftOnChainImageUrl;
  nft_text_front_image_url?: CampaignPromotionNftTextFrontImageUrl;
  nft_text_front_video_url?: CampaignPromotionNftTextFrontVideoUrl;
  promotion?: CampaignPromotionPromotion;
  minted_by_user?: CampaignPromotionMintedByUser;
}

export type Chain = (typeof Chain)[keyof typeof Chain];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Chain = {
  ton: "ton",
  sol: "sol",
  eth: "eth",
  soon: "soon",
  berachain: "berachain",
} as const;

export type CodeType = (typeof CodeType)[keyof typeof CodeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CodeType = {
  limited: "limited",
  unlimited: "unlimited",
  gunlimited: "gunlimited",
} as const;

export interface DiscordAuthCode {
  code: string;
}

export type EligibleFirstReqWallet = string | null;

export type EligibleFirstReqChain = Chain | null;

export type EligibleFirstReqReferralCode = string | null;

export type EligibleFirstReqDiscordCode = string | null;

export interface EligibleFirstReq {
  wallet?: EligibleFirstReqWallet;
  chain?: EligibleFirstReqChain;
  referral_code?: EligibleFirstReqReferralCode;
  discord_code?: EligibleFirstReqDiscordCode;
}

export type EligibleMethod =
  (typeof EligibleMethod)[keyof typeof EligibleMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EligibleMethod = {
  eth: "eth",
  sol: "sol",
  ton: "ton",
  soon: "soon",
  berachain: "berachain",
  referral: "referral",
  c_referral: "c_referral",
  bypass: "bypass",
  discord: "discord",
} as const;

export type EligibleRespMsg = string | null;

export interface EligibleResp {
  is_eligible: boolean;
  msg?: EligibleRespMsg;
}

export type EligibleResultToken = string | null;

export interface EligibleResult {
  req: EligibleFirstReq;
  campaigns: number[];
  token?: EligibleResultToken;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface MintGasReq {
  transaction_hash: string;
  nft_id: number;
}

export type NftStatus = (typeof NftStatus)[keyof typeof NftStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NftStatus = {
  new: "new",
  paid: "paid",
  payment_confirmed: "payment_confirmed",
  minted: "minted",
  mint_failed: "mint_failed",
  payment_expired: "payment_expired",
} as const;

export type ProductDescription = string | null;

export type ProductImageUrl = string | null;

export type ProductVideoUrl = string | null;

export interface Product {
  id: number;
  name: string;
  description?: ProductDescription;
  image_url?: ProductImageUrl;
  video_url?: ProductVideoUrl;
}

export interface PromoteCompleteResp {
  network: Chain;
  name: string;
  symbol: string;
  nft_id: number;
  gas_fee: number;
  status: NftStatus;
}

export type PromoteNftSeq = number | null;

export type PromoteNftName = string | null;

export type PromoteNftSymbol = string | null;

export type PromoteNftImageUrl = string | null;

export type PromoteNftVideoUrl = string | null;

export type PromoteNftOnChainImageUrl = string | null;

export type PromoteNftMinted = boolean | null;

export type PromoteNftMintedTimes = number | null;

export type PromoteNftIsOnChain = boolean | null;

export type PromoteNftTokenAddress = string | null;

export type PromoteNftCollectionAddress = string | null;

export type PromoteNftXPostUrl = string | null;

export type PromoteNftReferralId = number | null;

export type PromoteNftReferralCode = string | null;

export type PromoteNftCreatedAt = string | null;

export type PromoteNftStatus = NftStatus | null;

export type PromoteNftMintedAt = string | null;

export interface PromoteNft {
  user_id: string;
  campaign_id: number;
  promotion_id: number;
  seq?: PromoteNftSeq;
  name?: PromoteNftName;
  symbol?: PromoteNftSymbol;
  image_url?: PromoteNftImageUrl;
  video_url?: PromoteNftVideoUrl;
  on_chain_image_url?: PromoteNftOnChainImageUrl;
  minted?: PromoteNftMinted;
  minted_times?: PromoteNftMintedTimes;
  is_on_chain?: PromoteNftIsOnChain;
  token_address?: PromoteNftTokenAddress;
  collection_address?: PromoteNftCollectionAddress;
  x_post_url?: PromoteNftXPostUrl;
  referral_id?: PromoteNftReferralId;
  referral_code?: PromoteNftReferralCode;
  created_at?: PromoteNftCreatedAt;
  status?: PromoteNftStatus;
  minted_at?: PromoteNftMintedAt;
}

export interface PromoteReferralReq {
  referral_code: string;
}

export type PromotionName = string | null;

export type PromotionDescription = string | null;

export type PromotionImageUrl = string | null;

export type PromotionVideoUrl = string | null;

export type PromotionNftName = string | null;

export type PromotionNftSymbol = string | null;

export type PromotionNftDescription = string | null;

export type PromotionNftMetaUrl = string | null;

export type PromotionNftCollectionId = string | null;

export interface Promotion {
  promotion_id: number;
  name?: PromotionName;
  description?: PromotionDescription;
  image_url?: PromotionImageUrl;
  video_url?: PromotionVideoUrl;
  nft_name?: PromotionNftName;
  nft_symbol?: PromotionNftSymbol;
  nft_description?: PromotionNftDescription;
  nft_meta_url?: PromotionNftMetaUrl;
  nft_collection_id?: PromotionNftCollectionId;
}

export type ReferralUserId = string | null;

export type ReferralEnabled = boolean | null;

export interface Referral {
  user_id?: ReferralUserId;
  enabled?: ReferralEnabled;
  code_type: CodeType;
  code_level?: number;
  campaign_id: number;
  max_uses: number;
  current_uses: number;
}

export interface ReferralResp {
  wallet: string;
  campaign_id: number;
  timestamp: number;
}

export type SessionInfoMessage = string | null;

export interface SessionInfo {
  session_id: string;
  message?: SessionInfoMessage;
  chain?: Chain;
}

export type SignInVerifyData = TonSignProof | SolSignProof;

export interface SignInVerify {
  session_id: string;
  data: SignInVerifyData;
}

export interface SolSignProof {
  signature: string;
  address: string;
}

export interface SuccessResp {
  status?: string;
}

export interface TokenResp {
  token: string;
}

export interface TonSignProof {
  signature: string;
  state_init: string;
  timestamp: number;
  public_key: string;
  wallet_address_hex: string;
  wallet_address_base64: string;
}

export interface TwitterOauth {
  auth_code: string;
  redirect_url: string;
}

export interface UpdateEmailReq {
  email: string;
}

export type UserWalletAddressHex = string | null;

export type UserEthWalletAddress = string | null;

export type UserTonWalletAddress = string | null;

export type UserTwitterId = string | null;

export type UserTwitterName = string | null;

export type UserTwitterIconUrl = string | null;

export type UserTwitterLocked = boolean | null;

export type UserEmail = string | null;

export type UserPoints = number | null;

export type UserReferralCode = string | null;

export type UserCreatedAt = string | null;

export type UserUpdatedAt = string | null;

export interface User {
  user_id: string;
  wallet_address: string;
  wallet_address_hex?: UserWalletAddressHex;
  eth_wallet_address?: UserEthWalletAddress;
  ton_wallet_address?: UserTonWalletAddress;
  twitter_id?: UserTwitterId;
  twitter_name?: UserTwitterName;
  twitter_icon_url?: UserTwitterIconUrl;
  twitter_locked?: UserTwitterLocked;
  email?: UserEmail;
  chain: Chain;
  points?: UserPoints;
  referral_code?: UserReferralCode;
  created_at?: UserCreatedAt;
  updated_at?: UserUpdatedAt;
  user_activities?: UserActivity[];
  referrals?: Referral[];
  nfts?: PromoteNft[];
  eligibles?: UserCampaignEligible[];
  user_campaign_activities?: UserCampaignActivity[];
  products?: UserProduct[];
}

export type UserActivityUserActivityId = number | null;

export type UserActivityPoints = number | null;

export type UserActivityCampaignId = number | null;

export type UserActivityCompletedAt = string | null;

export type UserActivityActivityDataAnyOf = { [key: string]: unknown };

export type UserActivityActivityData = UserActivityActivityDataAnyOf | null;

export type UserActivityUser = User | null;

export type UserActivityActivity = Activity | null;

export type UserActivityCampaign = Campaign | null;

export interface UserActivity {
  user_activity_id?: UserActivityUserActivityId;
  user_id: string;
  activity_id: number;
  points?: UserActivityPoints;
  campaign_id?: UserActivityCampaignId;
  completed_at?: UserActivityCompletedAt;
  activity_data?: UserActivityActivityData;
  user?: UserActivityUser;
  activity?: UserActivityActivity;
  campaign?: UserActivityCampaign;
}

export type UserCampaignActivityCampaignActivity = CampaignActivity | null;

export interface UserCampaignActivity {
  campaign_activity?: UserCampaignActivityCampaignActivity;
  user_completed: number;
}

export type UserCampaignEligibleId = number | null;

export type UserCampaignEligibleIsEligible = boolean | null;

export type UserCampaignEligibleEligibleMethod = EligibleMethod | null;

export type UserCampaignEligibleEligibleWallet = string | null;

export interface UserCampaignEligible {
  id?: UserCampaignEligibleId;
  user_id: string;
  campaign_id: number;
  is_eligible?: UserCampaignEligibleIsEligible;
  eligible_method?: UserCampaignEligibleEligibleMethod;
  eligible_wallet?: UserCampaignEligibleEligibleWallet;
}

export type UserProductId = string | null;

export type UserProductSource = string | null;

export type UserProductCreatedAt = string | null;

export type UserProductProduct = Product | null;

export interface UserProduct {
  id?: UserProductId;
  product_id: number;
  user_id: string;
  source?: UserProductSource;
  created_at?: UserProductCreatedAt;
  product?: UserProductProduct;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type VmType = (typeof VmType)[keyof typeof VmType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VmType = {
  svm: "svm",
  evm: "evm",
  tvm: "tvm",
} as const;

export interface WalletRequest {
  wallet_address: string;
}

export type CheckEligibleDryrunCampaignsCampaignCheckEligibleDryrunGetParams = {
  /**
   * Ethereum wallet address
   */
  wallet: string;
};

export type CheckUserCampaignAlreadyPaidCampaignsCampaignPromotionPromotionIdAlreadyPaidGetParams =
  {
    after?: number | null;
  };

export type SetReferralRelationDryrunCampaignsCampaignReferralDryrunGetParams =
  {
    referral_code: string;
  };

export type GetDiscordAuthCodeCampaignsCampaignDiscordAuthCodeGetParams = {
  discord_id: string;
};
